# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvis(object):
    def setupUi(self, jarvis):
        jarvis.setObjectName("jarvis")
        jarvis.resize(1426, 631)
        self.centralwidget = QtWidgets.QWidget(jarvis)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -30, 1441, 791))
        self.label.setStyleSheet("background:transparent;\n"
"border radius:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("jarvis.gif"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1090, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 401, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Jarvis_Loading_Screen.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(405, 10, 281, 41))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(700, 10, 256, 41))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        jarvis.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvis)
        QtCore.QMetaObject.connectSlotsByName(jarvis)

    def retranslateUi(self, jarvis):
        _translate = QtCore.QCoreApplication.translate
        jarvis.setWindowTitle(_translate("jarvis", "MainWindow"))
        self.pushButton.setText(_translate("jarvis", "Run"))
        self.pushButton_2.setText(_translate("jarvis", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvis = QtWidgets.QMainWindow()
    ui = Ui_jarvis()
    ui.setupUi(jarvis)
    jarvis.show()
    sys.exit(app.exec_())
